version: '3.8'

services:
  web:
    container_name: <APP_NAME>
    build: .
    volumes:
      - static_volume:/staticfiles
      - db_volume:/db
    ports:
      - 8000:8000
    env_file:
      - .env
  
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/nginx/letsencrypt
      - static_volume:/staticfiles
      - certbot_www:/var/www/certbot
    ports:
      - 80:80
      - 443:443

volumes:
  static_volume:
  db_volume:
  certbot_www: